### ISSUE TITLE
Create MongoDB to store user settings on Oauth Flow

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/SimpleAlerts#1]
The flow of the app should go as follows:

1. Hit SimpleAlerts page, "Sign In With Twitch"
2. Oauth flow happens, brought to home screen
3. Check to see if user already exists by twitch user ID
4. If exists, load in their settings
5. If not exists, create document to store settings in DB

Seems like a good flow!

**Comment by Christian7573** [comment]
What's MongoDB? is it just something like MySQL?

**Comment by adilanchian** [comment]
MongoDB is a NoSQL, Document database system! It uses docs and objects instead of Tables like SQL. On top of it if all, it has a node.js driver which makes it perfect for this project!

**Comment by adilanchian** [comment]
This flow has been created. 
This may change depending on what settings we decide to pass back to angular.
