### ISSUE TITLE
Create UI that handles filters

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/SimpleAlerts#14]
In this issue I want to make sure I create UI that will handle the interaction with filters. Essentially this will turn into creating the event list component layout. These are the top things I should hit before closing this out:

### All Events
- [x] Toggle ALL filters on or off
- [x] Toggle order by timestamp threshold on or off

### Subscriptions
- [x] Toggle order by months on or off
   - [x] When toggle is on, add input of months threshold
- [x] Toggle order by tier on or off
   - [x] When toggle is on, add input of tier level threshold

### Cheer/Donation
- [x] Toggle order by amount on or off
   - [x] When only cheer event toggled on, add input of cheer threshold
   - [x] When only donation event toggled on, add input for donation threshold
   - [x] When both donation & cheer event toggled on, add input for both thresholds

**Comment by adilanchian** [comment]
I setup the initial layout for the event list component and included a new way to turn on/off listening to certain events.

Next step is to begin with the all events filter toggle

**Comment by adilanchian** [comment]
Updated the sketch doc with beginning thoughts of edit screen design and added Material design for ease. 

Need to start wiring up the toggle button for all filters next

**Comment by adilanchian** [comment]
INPUT STUFF IS JANK A F. Please wrap around before closing this.

**Comment by adilanchian** [comment]
All Event filters are good to go! Moving onto other filters.

**Comment by adilanchian** [comment]
Added subs filter by months, but need to triple check functionally is working!

**Comment by adilanchian** [comment]
I added the order by tier ui and functionality. Moving on to the next step of cheer/donations.

Now onto donations and cheers. These should be very similar so I can knock it out pretty quick

**Comment by adilanchian** [comment]
Okay all the input UI is setup and ready to go! Here are the list of things that need to be complete before closing out this ticket:

- [ ] Fix input UI as it does not show up until you click on it
- [x] Make the display list the height of the component and add scrolling
- [x] Triple check that the values for the filters are getting applied
- [x] Need to update UI when the All Filters toggle stuff is messed around with
- [x] Need to remove the cancel button and add a 'Done' button

**Comment by adilanchian** [comment]
Cannot get rid of scroll bar as I believe it might be bound to the OS and it is not worth researching this further.

**Comment by adilanchian** [comment]
Last thing for this ticket is to fix that weird input issue where it does not show up until clicked on...

**Comment by adilanchian** [comment]
Officially DONE! Closing.

**Comment by DigitalData** [comment]
This is like a conversation you're having with yourself.
