### ISSUE TITLE
Refresh & Auth Handeling

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/SimpleAlerts#19]
For some reason, I am required to authenticate with Streamlabs every time I hit the root route. Going to make sure that this is just for testing purposes and will not happen every time.

On refresh when on the dashboard the app does not return the token which means everything breaks. Need to figure out a proper refresh method.

**Comment by adilanchian** [comment]
Fixed page refresh issue and realized I was in the wrong branch. Cutting off another branch to keep working on this

**Comment by adilanchian** [comment]
I think this approval is happening on testing only... Once live, will test this out so good to go!

**Comment by DigitalData** [comment]
Title is misspelled.
